from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    ProjectMiddleLayerBatchCompileAPIView,
    ProjectMiddleLayerCollaborationSessionAcquireAPIView,
    ProjectMiddleLayerCollaborationSessionHeartbeatAPIView,
    ProjectMiddleLayerCollaborationSessionReleaseAPIView,
    ProjectCreationWizardCompileAPIView,
    ProjectCreationWizardStartAPIView,
    ProjectCreationWizardTagsAPIView,
    ProjectMiddleLayerCompileAPIView,
    ProjectMiddleLayerExportAPIView,
    IntegrationInboundSyncAPIView,
    IntegrationOutboundSyncAPIView,
    ProjectMiddleLayerSearchAPIView,
    ProjectMiddleLayerAnalyticsAPIView,
    ProjectMiddleLayerVersionCommitAPIView,
    ProjectMiddleLayerVersionCheckoutAPIView,
    ProjectMiddleLayerMergeAPIView,
    ProjectMiddleLayerPipelineRunAPIView,
    ProjectMiddleLayerScheduleRunAPIView,
    ProjectNodeViewSet,
    MarketplaceListAPIView,
    MarketplaceInstallAPIView,
    ExtensionApplyAPIView,
    ExtensionRollbackAPIView,
    GatewayIntrospectionAPIView,
    GatewayDispatchAPIView,
    BtifPlusExportAPIView,
    BtifPlusValidateAPIView,
    ExternalAgentRegisterAPIView,
    ExternalAgentRunAPIView,
    CrossSyncAPIView,
)

router = DefaultRouter()
router.register(r"nodes", ProjectNodeViewSet, basename="project-middle-layer-nodes")

urlpatterns = [
    path("compile/", ProjectMiddleLayerCompileAPIView.as_view(), name="project-middle-layer-compile"),
    path("compile/batch/", ProjectMiddleLayerBatchCompileAPIView.as_view(), name="project-middle-layer-compile-batch"),
    path("export/", ProjectMiddleLayerExportAPIView.as_view(), name="project-middle-layer-export"),
    path("pipelines/run/", ProjectMiddleLayerPipelineRunAPIView.as_view(), name="project-middle-layer-pipeline-run"),
    path("schedules/run/", ProjectMiddleLayerScheduleRunAPIView.as_view(), name="project-middle-layer-schedule-run"),
    path("integrations/inbound-sync/", IntegrationInboundSyncAPIView.as_view(), name="project-middle-layer-integration-inbound-sync"),
    path("integrations/outbound-sync/", IntegrationOutboundSyncAPIView.as_view(), name="project-middle-layer-integration-outbound-sync"),
    path("search/", ProjectMiddleLayerSearchAPIView.as_view(), name="project-middle-layer-search"),
    path("analytics/", ProjectMiddleLayerAnalyticsAPIView.as_view(), name="project-middle-layer-analytics"),
    path("versions/commit/", ProjectMiddleLayerVersionCommitAPIView.as_view(), name="project-middle-layer-version-commit"),
    path("versions/checkout/", ProjectMiddleLayerVersionCheckoutAPIView.as_view(), name="project-middle-layer-version-checkout"),
    path("merge/", ProjectMiddleLayerMergeAPIView.as_view(), name="project-middle-layer-merge"),
    path("collaboration/sessions/acquire/", ProjectMiddleLayerCollaborationSessionAcquireAPIView.as_view(), name="project-middle-layer-collaboration-session-acquire"),
    path("collaboration/sessions/heartbeat/", ProjectMiddleLayerCollaborationSessionHeartbeatAPIView.as_view(), name="project-middle-layer-collaboration-session-heartbeat"),
    path("collaboration/sessions/release/", ProjectMiddleLayerCollaborationSessionReleaseAPIView.as_view(), name="project-middle-layer-collaboration-session-release"),
    path("wizard/start/", ProjectCreationWizardStartAPIView.as_view(), name="project-middle-layer-wizard-start"),
    path("wizard/<str:wizard_id>/tags/", ProjectCreationWizardTagsAPIView.as_view(), name="project-middle-layer-wizard-tags"),
    path("wizard/<str:wizard_id>/compile/", ProjectCreationWizardCompileAPIView.as_view(), name="project-middle-layer-wizard-compile"),
    path("marketplace/", MarketplaceListAPIView.as_view(), name="project-middle-layer-marketplace-list"),
    path("marketplace/install/", MarketplaceInstallAPIView.as_view(), name="project-middle-layer-marketplace-install"),
    path("extensions/apply/", ExtensionApplyAPIView.as_view(), name="project-middle-layer-extension-apply"),
    path("extensions/rollback/", ExtensionRollbackAPIView.as_view(), name="project-middle-layer-extension-rollback"),
    path("gateway/introspect/", GatewayIntrospectionAPIView.as_view(), name="project-middle-layer-gateway-introspect"),
    path("gateway/dispatch/", GatewayDispatchAPIView.as_view(), name="project-middle-layer-gateway-dispatch"),
    path("btif-plus/export/", BtifPlusExportAPIView.as_view(), name="project-middle-layer-btif-plus-export"),
    path("btif-plus/validate/", BtifPlusValidateAPIView.as_view(), name="project-middle-layer-btif-plus-validate"),
    path("external-agents/register/", ExternalAgentRegisterAPIView.as_view(), name="project-middle-layer-external-agent-register"),
    path("external-agents/run/", ExternalAgentRunAPIView.as_view(), name="project-middle-layer-external-agent-run"),
    path("cross-sync/run/", CrossSyncAPIView.as_view(), name="project-middle-layer-cross-sync-run"),
    path("", include(router.urls)),
]
