# Generated by Django 6.0.5 on 2026-07-04 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('FINANCIALS', 'Financials'), ('COMMUNICATIONS', 'Communications'), ('CONSUMER', 'Consumer'), ('INDUSTRIALS', 'Industrials')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required_components', models.JSONField(default=list, help_text='Required fields for patterns in this industry')),
                ('pattern_constraints', models.JSONField(default=list, help_text='Constraints specific to this industry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Industry Profiles',
                'ordering': ['industry'],
            },
        ),
        migrations.CreateModel(
            name='PatternTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mlas_color', models.CharField(max_length=20)),
                ('pattern_type', models.CharField(max_length=50)),
                ('template_structure', models.JSONField(help_text='Reusable template structure')),
                ('description', models.TextField(blank=True)),
                ('example_input', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mlas_color', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TierDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], help_text='Complexity level: 1-3')),
                ('mlas_color', models.CharField(choices=[('RED', 'Red - Detection'), ('BLUE', 'Blue - Communication'), ('YELLOW', 'Yellow - Distribution'), ('GREEN', 'Green - Repair'), ('PURPLE', 'Purple - Branching'), ('TEAL', 'Teal - Replication'), ('ORANGE', 'Orange - Formation'), ('LIME', 'Lime - Publication'), ('PINK', 'Pink - Structure'), ('CYAN', 'Cyan - Function'), ('AMBER', 'Amber - Genetics'), ('GREEN_LIME', 'Green-Lime - Evolution')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pattern_type', models.CharField(help_text='Pattern classification', max_length=50)),
                ('complexity', models.IntegerField(help_text='Complexity rating 1-3')),
                ('required_fields', models.JSONField(default=dict, help_text='Required output fields for this tier')),
                ('behaviors', models.JSONField(default=list, help_text='Behaviors this tier should exhibit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_definitions', to='baseture_engine.industryprofile')),
            ],
            options={
                'ordering': ['tier_level', 'mlas_color'],
                'unique_together': {('tier_level', 'mlas_color', 'industry')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_input', models.CharField(help_text='The seed subject or input prompt', max_length=500)),
                ('output', models.JSONField(help_text='Generated tier structure')),
                ('rationale', models.TextField(blank=True, help_text='Explanation of how the output was generated')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='generated', max_length=20)),
                ('constraints_validated', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tiers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tier_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tiers', to='baseture_engine.tierdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='baseture_en_created_f28292_idx'), models.Index(fields=['status'], name='baseture_en_status_5e0b92_idx')],
            },
        ),
    ]
