# Generated by Django 6.0.5 on 2026-07-04 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseture_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SVEMTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_number', models.IntegerField(choices=[(1, 'Branch 1'), (2, 'Branch 2'), (3, 'Branch 3'), (4, 'Branch 4')], help_text='Branch 1-4 under parent tier')),
                ('seed_input', models.CharField(help_text='Seed from parent + branch specialization', max_length=500)),
                ('mlas_color', models.CharField(help_text='Inherited MLAS color from parent', max_length=20)),
                ('industry', models.CharField(help_text='Inherited industry from parent', max_length=50)),
                ('output', models.JSONField(help_text='Generated SVEM branch structure')),
                ('rationale', models.TextField(blank=True, help_text='Explanation of branch generation')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='generated', max_length=20)),
                ('constraints_validated', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svem_branches', to='baseture_engine.generatedtier')),
            ],
            options={
                'ordering': ['parent_tier', 'branch_number'],
            },
        ),
        migrations.CreateModel(
            name='CCCPTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_number', models.IntegerField(choices=[(1, 'Compartment 1'), (2, 'Compartment 2'), (3, 'Compartment 3'), (4, 'Compartment 4')], help_text='Compartment 1-4 under parent SVEM branch')),
                ('seed_input', models.CharField(help_text='Seed from parent SVEM + compartment specialization', max_length=500)),
                ('mlas_color', models.CharField(help_text='Inherited MLAS color from root tier', max_length=20)),
                ('industry', models.CharField(help_text='Inherited industry from root tier', max_length=50)),
                ('output', models.JSONField(help_text='Generated CCCP compartment structure')),
                ('rationale', models.TextField(blank=True, help_text='Explanation of compartment generation')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='generated', max_length=20)),
                ('constraints_validated', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_svem_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cccp_compartments', to='baseture_engine.svemtier')),
            ],
            options={
                'ordering': ['parent_svem_tier', 'compartment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='svemtier',
            index=models.Index(fields=['parent_tier', 'branch_number'], name='baseture_en_parent__8f20c0_idx'),
        ),
        migrations.AddIndex(
            model_name='svemtier',
            index=models.Index(fields=['-created_at'], name='baseture_en_created_e6ab98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='svemtier',
            unique_together={('parent_tier', 'branch_number')},
        ),
        migrations.AddIndex(
            model_name='cccptier',
            index=models.Index(fields=['parent_svem_tier', 'compartment_number'], name='baseture_en_parent__91c90f_idx'),
        ),
        migrations.AddIndex(
            model_name='cccptier',
            index=models.Index(fields=['-created_at'], name='baseture_en_created_aad924_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cccptier',
            unique_together={('parent_svem_tier', 'compartment_number')},
        ),
    ]
