# Generated by Django 6.0.5 on 2026-07-04 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseture_engine', '0002_svemtier_cccptier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCHDTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcell_number', models.IntegerField(choices=[(1, 'Subcell 1'), (2, 'Subcell 2'), (3, 'Subcell 3'), (4, 'Subcell 4')], help_text='Subcell 1-4 under parent CCCP compartment')),
                ('seed_input', models.CharField(help_text='Seed from parent CCCP + subcell specialization', max_length=500)),
                ('mlas_color', models.CharField(help_text='Inherited MLAS color from root tier', max_length=20)),
                ('industry', models.CharField(help_text='Inherited industry from root tier', max_length=50)),
                ('output', models.JSONField(help_text='Generated DCHD subcell structure')),
                ('rationale', models.TextField(blank=True, help_text='Explanation of subcell generation')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='generated', max_length=20)),
                ('constraints_validated', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_cccp_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dchd_subcells', to='baseture_engine.cccptier')),
            ],
            options={
                'ordering': ['parent_cccp_tier', 'subcell_number'],
                'indexes': [models.Index(fields=['parent_cccp_tier', 'subcell_number'], name='baseture_en_parent__dcaeb0_idx'), models.Index(fields=['-created_at'], name='baseture_en_created_1f6c19_idx')],
                'unique_together': {('parent_cccp_tier', 'subcell_number')},
            },
        ),
    ]
