# Generated by Django 6.0.5 on 2026-07-05 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseture_engine', '0003_dchdtier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryScaffold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(help_text='Unique key within root hierarchy, e.g. svem:12', max_length=80)),
                ('node_type', models.CharField(choices=[('root', 'Root'), ('svem', 'SVEM'), ('cccp', 'CCCP'), ('dchd', 'DCHD')], max_length=10)),
                ('node_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timeline_lattice_index', models.IntegerField(blank=True, null=True)),
                ('timeline_label', models.CharField(blank=True, max_length=120)),
                ('semantic_intent_id', models.CharField(blank=True, max_length=120)),
                ('talking_points', models.TextField(blank=True)),
                ('core_concept', models.TextField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('chapter_structure', models.TextField(blank=True)),
                ('dchd_atoms', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('root_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_scaffolds', to='baseture_engine.generatedtier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_story_scaffolds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['root_tier', 'node_key'],
                'indexes': [models.Index(fields=['root_tier', 'node_key'], name='baseture_en_root_ti_3144bf_idx'), models.Index(fields=['root_tier', '-updated_at'], name='baseture_en_root_ti_bb8d2a_idx')],
                'unique_together': {('root_tier', 'node_key')},
            },
        ),
    ]
