# Generated by Django 6.0.5 on 2026-07-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseture_engine', '0004_storyscaffold'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyscaffold',
            name='scaffold_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
