# Generated by Django 6.0.5 on 2026-07-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish', '0012_taskmanageranalyticsexportrun_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachmentauditlog',
            name='event_type',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('removed', 'Removed'), ('review_approved', 'Review Approved'), ('review_rescanned', 'Review Rescanned'), ('review_deleted', 'Review Deleted')], max_length=16),
        ),
    ]
