# Generated by Django 6.0.5 on 2026-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish', '0014_taskworkflowdriftsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='polishtask',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='sectoragenda',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='taskobjective',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
    ]
