# Generated by Copilot on 2026-07-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_middle_layer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEvolutionSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("identity_payload", models.JSONField(default=dict)),
                ("drift_forecast", models.JSONField(default=dict)),
                ("branch_resolution", models.JSONField(default=dict)),
                ("specialized_path", models.JSONField(default=dict)),
                ("semantic_tags", models.JSONField(default=list)),
                ("identity_uri", models.CharField(max_length=255)),
                ("branch_name", models.CharField(blank=True, max_length=120)),
                ("drift_risk", models.FloatField(default=0.0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolution_snapshots",
                        to="project_middle_layer.projectnode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
