# Generated by Django 5.2.6 on 2026-07-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_middle_layer", "0014_semantic_distribution_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAgent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("endpoint", models.URLField(max_length=500)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("auth_token", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled")], default="active", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="MarketplaceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("item_type", models.CharField(choices=[("plugin", "Plugin"), ("schema", "Schema"), ("agent", "Agent"), ("extension", "Extension")], max_length=20)),
                ("current_version", models.CharField(default="0.0.1", max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SemanticCrossSyncLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sync_type", models.CharField(choices=[("full", "Full Sync"), ("delta", "Delta Sync"), ("version", "Version Sync"), ("lineage", "Lineage Sync"), ("analytics", "Analytics Sync"), ("insight", "Insight Sync")], max_length=20)),
                ("source_platform", models.CharField(default="local", max_length=120)),
                ("target_platform", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="running", max_length=20)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("conflict_report", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-started_at", "-id"]},
        ),
        migrations.CreateModel(
            name="SemanticExtension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("schema_patch", models.JSONField(blank=True, default=dict)),
                ("rules_patch", models.JSONField(blank=True, default=dict)),
                ("version", models.CharField(default="0.0.1", max_length=40)),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_payload", models.JSONField(blank=True, default=dict)),
                ("validation_report", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SemanticPlugin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("plugin_type", models.CharField(default="agent", max_length=40)),
                ("entrypoint", models.CharField(max_length=255)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("version", models.CharField(default="0.0.1", max_length=40)),
                ("enabled", models.BooleanField(default=False)),
                ("last_status", models.CharField(default="idle", max_length=20)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="MarketplaceInstall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("installed_version", models.CharField(max_length=40)),
                ("status", models.CharField(choices=[("installed", "Installed"), ("updating", "Updating"), ("failed", "Failed"), ("removed", "Removed")], default="installed", max_length=20)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="installs", to="project_middle_layer.marketplaceitem")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="marketplace_installs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="MarketplaceVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=40)),
                ("changelog", models.TextField(blank=True)),
                ("compatibility", models.JSONField(blank=True, default=dict)),
                ("dependency_slugs", models.JSONField(blank=True, default=list)),
                ("download_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="project_middle_layer.marketplaceitem")),
            ],
            options={"ordering": ["-created_at", "-id"], "unique_together": {("item", "version")}},
        ),
    ]
