from django.urls import include, path

from .views import (
    ProjectMiddleLayerBatchCompileView,
    ProjectMiddleLayerCompileView,
    ProjectMiddleLayerAlertsView,
    ProjectMiddleLayerDiffView,
    ProjectMiddleLayerExportView,
    ProjectMiddleLayerPipelinesView,
    ProjectMiddleLayerPipelineRunView,
    ProjectMiddleLayerSchedulesView,
    ProjectMiddleLayerScheduleRunView,
    ProjectMiddleLayerSchedulePauseView,
    ProjectMiddleLayerWebhooksView,
    ProjectMiddleLayerWebhookRetryView,
    ProjectMiddleLayerIntegrationsView,
    ProjectMiddleLayerIntegrationOutboundSyncView,
    ProjectMiddleLayerAnalyticsView,
    ProjectMiddleLayerDashboardView,
    ProjectMiddleLayerSearchView,
    ProjectMiddleLayerInsightsView,
    ProjectMiddleLayerRolesView,
    ProjectMiddleLayerCollaborationView,
    ProjectMiddleLayerChangeRequestsView,
    ProjectMiddleLayerAuditView,
    ProjectMiddleLayerVersionsView,
    ProjectMiddleLayerMergeView,
    ProjectMiddleLayerAgentsView,
    ProjectMiddleLayerLineageExplorerView,
    ProjectMiddleLayerRecommendationsView,
    ProjectMiddleLayerStatusView,
    ProjectMiddleLayerTimelineView,
    ProjectMiddleLayerReplicationView,
    ProjectMiddleLayerFederationView,
    ProjectMiddleLayerShardsView,
    ProjectMiddleLayerCacheView,
    ProjectMiddleLayerSyncView,
    ProjectMiddleLayerDistributedAgentsView,
    ProjectMiddleLayerMarketplaceView,
    ProjectMiddleLayerPluginsView,
    ProjectMiddleLayerExtensionsView,
    ProjectMiddleLayerGatewayView,
    ProjectMiddleLayerBtifPlusView,
    ProjectMiddleLayerExternalAgentsView,
    ProjectMiddleLayerCrossSyncView,
    ProjectMiddleLayerSeedDemoDataView,
)

app_name = "project_middle_layer"

urlpatterns = [
    path("", ProjectMiddleLayerStatusView.as_view(), name="status"),
    path("compile/", ProjectMiddleLayerCompileView.as_view(), name="compile"),
    path("batch-compile/", ProjectMiddleLayerBatchCompileView.as_view(), name="batch-compile"),
    path("export/", ProjectMiddleLayerExportView.as_view(), name="export"),
    path("pipelines/", ProjectMiddleLayerPipelinesView.as_view(), name="pipelines"),
    path("pipelines/<slug:slug>/run/", ProjectMiddleLayerPipelineRunView.as_view(), name="pipeline-run"),
    path("schedules/", ProjectMiddleLayerSchedulesView.as_view(), name="schedules"),
    path("schedules/<slug:slug>/run/", ProjectMiddleLayerScheduleRunView.as_view(), name="schedule-run"),
    path("schedules/<slug:slug>/pause/", ProjectMiddleLayerSchedulePauseView.as_view(), name="schedule-pause"),
    path("webhooks/", ProjectMiddleLayerWebhooksView.as_view(), name="webhooks"),
    path("webhooks/deliveries/<int:delivery_id>/retry/", ProjectMiddleLayerWebhookRetryView.as_view(), name="webhook-retry"),
    path("integrations/", ProjectMiddleLayerIntegrationsView.as_view(), name="integrations"),
    path("integrations/<slug:slug>/sync-outbound/", ProjectMiddleLayerIntegrationOutboundSyncView.as_view(), name="integration-sync-outbound"),
    path("analytics/", ProjectMiddleLayerAnalyticsView.as_view(), name="analytics"),
    path("dashboard/", ProjectMiddleLayerDashboardView.as_view(), name="dashboard"),
    path("search/", ProjectMiddleLayerSearchView.as_view(), name="search"),
    path("insights/", ProjectMiddleLayerInsightsView.as_view(), name="insights"),
    path("agents/", ProjectMiddleLayerAgentsView.as_view(), name="agents"),
    path("roles/", ProjectMiddleLayerRolesView.as_view(), name="roles"),
    path("collaboration/", ProjectMiddleLayerCollaborationView.as_view(), name="collaboration"),
    path("change-requests/", ProjectMiddleLayerChangeRequestsView.as_view(), name="change-requests"),
    path("audit/", ProjectMiddleLayerAuditView.as_view(), name="audit"),
    path("versions/", ProjectMiddleLayerVersionsView.as_view(), name="versions"),
    path("merge/", ProjectMiddleLayerMergeView.as_view(), name="merge"),
    path("timeline/", ProjectMiddleLayerTimelineView.as_view(), name="timeline"),
    path("lineage/", ProjectMiddleLayerLineageExplorerView.as_view(), name="lineage"),
    path("alerts/", ProjectMiddleLayerAlertsView.as_view(), name="alerts"),
    path("recommendations/", ProjectMiddleLayerRecommendationsView.as_view(), name="recommendations"),
    path("diff/", ProjectMiddleLayerDiffView.as_view(), name="diff"),
    path("replication/", ProjectMiddleLayerReplicationView.as_view(), name="replication"),
    path("federation/", ProjectMiddleLayerFederationView.as_view(), name="federation"),
    path("shards/", ProjectMiddleLayerShardsView.as_view(), name="shards"),
    path("cache/", ProjectMiddleLayerCacheView.as_view(), name="cache"),
    path("sync/", ProjectMiddleLayerSyncView.as_view(), name="sync"),
    path("distributed-agents/", ProjectMiddleLayerDistributedAgentsView.as_view(), name="distributed-agents"),
    path("marketplace/", ProjectMiddleLayerMarketplaceView.as_view(), name="marketplace"),
    path("plugins/", ProjectMiddleLayerPluginsView.as_view(), name="plugins"),
    path("extensions/", ProjectMiddleLayerExtensionsView.as_view(), name="extensions"),
    path("gateway/", ProjectMiddleLayerGatewayView.as_view(), name="gateway"),
    path("btif-plus/", ProjectMiddleLayerBtifPlusView.as_view(), name="btif-plus"),
    path("external-agents/", ProjectMiddleLayerExternalAgentsView.as_view(), name="external-agents"),
    path("cross-sync/", ProjectMiddleLayerCrossSyncView.as_view(), name="cross-sync"),
    path("seed-demo-data/", ProjectMiddleLayerSeedDemoDataView.as_view(), name="seed-demo-data"),
    path("api/", include("project_middle_layer.api.routes")),
]
