# Generated by Django 6.0.5 on 2026-08-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GICSReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('sector', 'Sector'), ('industry_group', 'Industry Group'), ('industry', 'Industry'), ('sub_industry', 'Sub-Industry')], db_index=True, default='sub_industry', max_length=24)),
                ('parent_code', models.CharField(blank=True, default='', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('source_version', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_core_gicsreference',
                'ordering': ['level', 'code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NAICSReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sector_code', models.CharField(blank=True, default='', max_length=12)),
                ('source_version', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_core_naicsreference',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformReferenceGICSReferenceSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('sector', 'Sector'), ('industry_group', 'Industry Group'), ('industry', 'Industry'), ('sub_industry', 'Sub-Industry')], db_index=True, default='sub_industry', max_length=24)),
                ('parent_code', models.CharField(blank=True, default='', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('source_version', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_reference_gicsreference',
                'ordering': ['level', 'code'],
                'managed': True,
                'indexes': [models.Index(fields=['level', 'code'], name='platform_re_level_gics_idx'), models.Index(fields=['parent_code', 'level'], name='pr_gics_parent_level_idx'), models.Index(fields=['is_active', 'level', 'code'], name='platform_re_is_active_gics_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'level'), name='platform_re_gics_code_level_unique')],
            },
        ),
        migrations.CreateModel(
            name='PlatformReferenceNAICSReferenceSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sector_code', models.CharField(blank=True, default='', max_length=12)),
                ('source_version', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_reference_naicsreference',
                'ordering': ['code'],
                'managed': True,
                'indexes': [models.Index(fields=['sector_code', 'code'], name='platform_re_sector__naics_idx'), models.Index(fields=['is_active', 'code'], name='pr_naics_active_code_idx')],
            },
        ),
    ]
