# Generated by Django 6.0.5 on 2026-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0005_business_rgb_identity_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='business',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='idea',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='seed',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('RAW', 'Raw'), ('SEED', 'Seed'), ('PROJECT', 'Project'), ('BUSINESS', 'Business (Legacy)')], default='RAW', max_length=16),
        ),
    ]
