# Generated by Django 6.0.5 on 2026-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=255)),
                ('degree_level_code', models.IntegerField(db_index=True)),
                ('degree_name', models.CharField(max_length=100)),
                ('career_title', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
