# Generated by Django 6.0.5 on 2026-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='career_title',
            field=models.CharField(max_length=255),
        ),
    ]
