# Generated by Django 6.0.5 on 2026-06-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_alter_careerpath_career_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerpath',
            options={'verbose_name': 'Career Path Assignment', 'verbose_name_plural': 'Career Path Assignments'},
        ),
        migrations.AddField(
            model_name='careerpath',
            name='salary_metric',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
