# Generated by Django 6.0.5 on 2026-06-24 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0004_prepopulate_additional_careerpaths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('degree_query', models.CharField(blank=True, default='', max_length=10)),
                ('sort_by', models.CharField(default='salary_desc', max_length=30)),
                ('selected_subjects', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Filter Preset',
                'verbose_name_plural': 'Career Filter Presets',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
