# Generated by Django 6.0.5 on 2026-06-26 03:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('acronym', models.CharField(max_length=8)),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'ordering': ['subject__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('acronym', models.CharField(max_length=8, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemporalSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tense', models.CharField(choices=[('past', 'Past'), ('present_past', 'Present-Past'), ('present_future', 'Present-Future'), ('future', 'Future')], max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('default_phase', models.CharField(choices=[('create', 'Create'), ('post', 'Post'), ('work', 'Work')], default='post', max_length=16)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='ontology.branch')),
            ],
            options={
                'ordering': ['branch__subject__order', 'branch__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='ontology.industry')),
            ],
            options={
                'ordering': ['industry__branch__subject__order', 'industry__branch__order', 'industry__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='ontology.subject'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_industry_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(fields=('branch', 'order'), name='uniq_industry_branch_order'),
        ),
        migrations.AddConstraint(
            model_name='subindustry',
            constraint=models.UniqueConstraint(fields=('industry', 'name'), name='uniq_subindustry_industry_name'),
        ),
        migrations.AddConstraint(
            model_name='subindustry',
            constraint=models.UniqueConstraint(fields=('industry', 'order'), name='uniq_subindustry_industry_order'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='uniq_branch_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('subject', 'order'), name='uniq_branch_subject_order'),
        ),
    ]
