"""
Django settings for gr_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Make BTIF app modules importable inside this Django project.
BTIF_BASE_DIR = BASE_DIR / "BTIF"
if BTIF_BASE_DIR.exists() and str(BTIF_BASE_DIR) not in sys.path:
    sys.path.append(str(BTIF_BASE_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#hsk+1qv3+o1jg1!jc6j!9+sg3ruon4p*5@ja$9-6)axb6+(ow'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'platform_core.apps.PlatformCoreConfig',
    'homepage_backend.apps.HomepageBackendConfig',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken', # For mobile/desktop login tokens
    # Installed Apps
    'users.apps.UsersConfig',
    'polls.apps.PollsConfig',
    'home.apps.HomeConfig',
    'center.apps.CenterConfig',
    'domain.apps.DomainConfig',
    'polish.apps.PolishConfig',
    'twist.apps.TwistConfig',
    'rhythmclock.apps.RhythmclockConfig',
    'peringram.apps.PeringramConfig',
    'seeds.apps.SeedsConfig',
    'problems.apps.ProblemsConfig',
    'povs.apps.PovsConfig',
    'forums.apps.ForumsConfig',
    'career_app.apps.CareerAppConfig',
    'baseTrue_news.apps.BasetrueNewsConfig',
    'ontology.apps.OntologyConfig',
    'support.apps.SupportConfig',
    'storytelling_dashboard.apps.StorytellingDashboardConfig',

    #Third Party Apps
    'bulma',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Protects endpoints by default
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

ROOT_URLCONF = 'gr_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gr_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'btgr_db',
        'USER': 'postgres',
        'PASSWORD': 'whoelse',
        'HOST': '127.0.0.1',
        'PORT': '5435',
    }
}

# CACHES
# https://docs.djangoproject.com/en/4.2/topics/cache/

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "127.0.0.1:11211",
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR  /'static']
STATIC_ROOT = BASE_DIR  /'staticfiles'

# Media files (user uploaded content)
# https://docs.djangoproject.com/en/4.2/ref/settings/#std:setting-MEDIA_ROOT
# https://docs.djangoproject.com/en/4.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


FIXTURE_DIRS = [BASE_DIR / 'fixtures']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://docs.djangoproject.com/en/dev/ref/settings/#auth-user-model
AUTH_USER_MODEL = "users.User"

LOGIN_REDIRECT_URL = "users:redirect"
LOGOUT_REDIRECT_URL = "/"

# Email settings for newsletter delivery
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", os.getenv("EMAIL_ADDRESS", ""))
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", os.getenv("EMAIL_PASSWORD", ""))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@basetrue.local")

# Billing webhook verification (Option C foundation)
BILLING_WEBHOOK_SECRET = os.getenv("BILLING_WEBHOOK_SECRET", "")
BILLING_WEBHOOK_SECRET_STRIPE = os.getenv("BILLING_WEBHOOK_SECRET_STRIPE", "")
BILLING_STRIPE_SIGNATURE_TOLERANCE_SECONDS = int(os.getenv("BILLING_STRIPE_SIGNATURE_TOLERANCE_SECONDS", "300"))
BILLING_STRIPE_SECRET_KEY = os.getenv("BILLING_STRIPE_SECRET_KEY", "")
BILLING_CHECKOUT_SUCCESS_URL = os.getenv(
    "BILLING_CHECKOUT_SUCCESS_URL",
    "http://localhost:8000/users/subscription/upgrade/?checkout=success",
)
BILLING_CHECKOUT_CANCEL_URL = os.getenv(
    "BILLING_CHECKOUT_CANCEL_URL",
    "http://localhost:8000/users/subscription/upgrade/?checkout=cancel",
)

_stripe_price_tier_map_raw = {
    os.getenv("BILLING_STRIPE_PRICE_PREMIUM_STARTER", ""): "premium_starter",
    os.getenv("BILLING_STRIPE_PRICE_PREMIUM_PRO", ""): "premium_pro",
    os.getenv("BILLING_STRIPE_PRICE_PREMIUM_ENTERPRISE", ""): "premium_enterprise",
}
BILLING_STRIPE_PRICE_TIER_MAP = {key: value for key, value in _stripe_price_tier_map_raw.items() if key}
