export const quadrantLinkConfig = {
  amDomains: {
    1: { slug: "bos", label: "BOS" },
    2: { slug: "bridge", label: "Bridge" },
    3: { slug: "openfields", label: "OpenFields" },
    4: { slug: "seedlings", label: "Seedlings" },
    5: { slug: "roots", label: "Roots" },
    6: { slug: "growth", label: "Growth" },
    7: { slug: "sunrise", label: "Sunrise" },
    8: { slug: "pathways", label: "Pathways" },
    9: { slug: "community", label: "Community" },
    10: { slug: "exchange", label: "Exchange" },
    11: { slug: "harvestprep", label: "HarvestPrep" },
    12: { slug: "harvestcrops", label: "HarvestCrops" },
  },
  pmDomains: {
    1: { slug: "bos-domain", label: "BOS Domain" },
    2: { slug: "bridge-domain", label: "Bridge Domain" },
    3: { slug: "openfields-domain", label: "OpenFields Domain" },
    4: { slug: "seedlings-domain", label: "Seedlings Domain" },
    5: { slug: "roots-domain", label: "Roots Domain" },
    6: { slug: "growth-domain", label: "Growth Domain" },
    7: { slug: "sunrise-domain", label: "Sunrise Domain" },
    8: { slug: "pathways-domain", label: "Pathways Domain" },
    9: { slug: "community-domain", label: "Community Domain" },
    10: { slug: "exchange-domain", label: "Exchange Domain" },
    11: { slug: "harvestprep-domain", label: "HarvestPrep Domain" },
    12: { slug: "harvestcrops-domain", label: "HarvestCrops Domain" },
  },
};
