# Generated by Django 6.0.5 on 2026-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pattern_tag',
            field=models.CharField(blank=True, choices=[('billing', 'Billing / Pricing'), ('ui', 'UI / Navigation'), ('feature', 'Feature Request'), ('bug', 'Bug / Error'), ('performance', 'Performance'), ('other', 'Other'), ('', 'Unclassified')], default='', help_text='Links this FAQ to a negative feedback pattern for auto-suggestion.', max_length=20),
        ),
    ]
