# Generated by Django 6.0.5 on 2026-07-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq_pattern_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-priority', 'order', 'id'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='faq',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Elevated'), (2, 'High'), (3, 'Critical')], default=0, help_text='Higher priority FAQs surface first in suggestions.'),
        ),
    ]
