# Generated by Django 6.0.5 on 2026-07-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_faq_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='negative_hits',
            field=models.PositiveIntegerField(default=0, help_text='Times negative feedback was submitted (proxy for unresolved issues).'),
        ),
        migrations.AddField(
            model_name='faq',
            name='positive_hits',
            field=models.PositiveIntegerField(default=0, help_text='Times this FAQ was viewed as a suggestion.'),
        ),
    ]
