# Generated by Django 6.0.5 on 2026-06-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('pressure_index', models.FloatField(default=0.0)),
                ('average_health_score', models.FloatField(default=0.0)),
                ('risk_flag_count', models.PositiveIntegerField(default=0)),
                ('activity_count', models.PositiveIntegerField(default=0)),
                ('user_growth_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insights Daily Snapshot',
                'verbose_name_plural': 'Insights Daily Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
