# Generated by Django 6.0.5 on 2026-06-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsNarrativeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('state_label', models.CharField(default='Stable', max_length=32)),
                ('pressure_index', models.FloatField(default=0.0)),
                ('weighted_priority_score', models.FloatField(default=0.0)),
                ('growth_direction', models.CharField(default='Mixed', max_length=32)),
                ('quadrant_priority', models.CharField(default='Green', max_length=16)),
                ('pipeline_bottleneck', models.CharField(default='N/A', max_length=120)),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('daily_brief', models.TextField(blank=True, default='')),
                ('weekly_summary', models.TextField(blank=True, default='')),
                ('monthly_outlook', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insights Narrative Snapshot',
                'verbose_name_plural': 'Insights Narrative Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
