# Generated by Django 6.0.5 on 2026-06-29 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0010_billing_access_links_and_notification_retries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phase', models.CharField(db_index=True, max_length=20)),
                ('color_primary', models.CharField(db_index=True, max_length=20)),
                ('metaphor', models.CharField(db_index=True, max_length=30)),
                ('mlas_subject', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('mlas_branch', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('mlas_term', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('mlas_meta', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('dewey_code', models.IntegerField(db_index=True)),
                ('industry_super_sector', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('industry_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_group', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_sub_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('ui_category', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('phase', models.CharField(choices=[('create', 'Create'), ('post', 'Post'), ('work', 'Work')], db_index=True, max_length=20)),
                ('color_primary', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('purple', 'Purple'), ('teal', 'Teal'), ('orange', 'Orange'), ('lime', 'Lime'), ('pink', 'Pink'), ('cyan', 'Cyan'), ('amber', 'Amber'), ('green-lime', 'Green-Lime')], db_index=True, max_length=20)),
                ('metaphor', models.CharField(choices=[('immune_system', 'Immune System'), ('mycelium', 'Mycelium'), ('botanist', 'Botanist')], db_index=True, max_length=30)),
                ('mlas_subject', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('mlas_branch', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('mlas_term', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('mlas_meta', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('dewey_code', models.IntegerField(db_index=True)),
                ('industry_super_sector', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('industry_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_group', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_sub_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('ui_category', models.CharField(blank=True, choices=[('operations', 'Operations'), ('customer', 'Customer'), ('delivery', 'Delivery'), ('executive', 'Executive')], db_index=True, max_length=30, null=True)),
                ('phase_resolved', models.CharField(db_index=True, max_length=20)),
                ('ui_category_resolved', models.CharField(db_index=True, max_length=30)),
                ('layout_archetype', models.CharField(db_index=True, max_length=30)),
                ('component_pack', models.CharField(db_index=True, max_length=30)),
                ('nav_group', models.CharField(db_index=True, max_length=30)),
                ('page_signature', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='platform_core.semanticpreset')),
            ],
        ),
        migrations.AddIndex(
            model_name='semanticpreset',
            index=models.Index(fields=['phase'], name='platform_co_phase_f49757_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticpreset',
            index=models.Index(fields=['color_primary'], name='platform_co_color_p_035f67_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticpreset',
            index=models.Index(fields=['mlas_subject', 'mlas_branch', 'mlas_term'], name='platform_co_mlas_su_298de9_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticpreset',
            index=models.Index(fields=['dewey_code'], name='platform_co_dewey_c_9aa9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['phase'], name='platform_co_phase_5a5180_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['color_primary'], name='platform_co_color_p_bc6e02_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['mlas_subject', 'mlas_branch', 'mlas_term'], name='platform_co_mlas_su_5b8c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['dewey_code'], name='platform_co_dewey_c_712864_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['industry_super_sector'], name='platform_co_industr_1cf543_idx'),
        ),
        migrations.AddIndex(
            model_name='slide',
            index=models.Index(fields=['ui_category_resolved'], name='platform_co_ui_cate_65e45c_idx'),
        ),
    ]
