# Generated by Django 6.0.5 on 2026-06-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0011_semanticpreset_slide_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractbillingaccesslink',
            new_name='platform_co_tenant__a4c302_idx',
            old_name='platform_cor_tenant__a643b4_idx',
        ),
        migrations.RenameIndex(
            model_name='contractbillingaccesslink',
            new_name='platform_co_is_acti_f1f4fc_idx',
            old_name='platform_cor_is_acti_049908_idx',
        ),
        migrations.RenameIndex(
            model_name='contractbillingjob',
            new_name='platform_co_status_6c2a6e_idx',
            old_name='platform_cor_status__2d5014_idx',
        ),
        migrations.RenameIndex(
            model_name='contractbillingjob',
            new_name='platform_co_tenant__a2f4ff_idx',
            old_name='platform_cor_tenant__13bfef_idx',
        ),
        migrations.RenameIndex(
            model_name='contractbillingnotification',
            new_name='platform_co_status_1eb7c9_idx',
            old_name='platform_cor_status__9613d6_idx',
        ),
        migrations.RenameIndex(
            model_name='contractbillingnotification',
            new_name='platform_co_tenant__f55559_idx',
            old_name='platform_cor_tenant__a83de9_idx',
        ),
        migrations.RenameIndex(
            model_name='contractbillingsnapshot',
            new_name='platform_co_tenant__97bc55_idx',
            old_name='platform_cor_tenant__44efe6_idx',
        ),
        migrations.RenameIndex(
            model_name='contractusageevent',
            new_name='platform_co_tenant__a42f7e_idx',
            old_name='platform_cor_tenant__7628ec_idx',
        ),
        migrations.RenameIndex(
            model_name='contractusageevent',
            new_name='platform_co_client__b6ce3d_idx',
            old_name='platform_cor_client__9f5ec8_idx',
        ),
        migrations.RenameIndex(
            model_name='contractusageevent',
            new_name='platform_co_endpoin_7c5f98_idx',
            old_name='platform_cor_endpoin_ef8a5f_idx',
        ),
        migrations.RenameIndex(
            model_name='contractusageevent',
            new_name='platform_co_status__221548_idx',
            old_name='platform_cor_status__51db4e_idx',
        ),
        migrations.AlterField(
            model_name='clientcontractprofile',
            name='overage_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contractbillingjob',
            name='job_type',
            field=models.CharField(choices=[('billing_cycle', 'Billing cycle'), ('invoice_export', 'Invoice export'), ('notify', 'Notify'), ('automation', 'Operational automation')], default='billing_cycle', max_length=32),
        ),
    ]
