# Generated by Django 6.0.5 on 2026-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0015_semanticbundleshare_and_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadrantUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField()),
                ('is_pm', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quadrant Usage Event',
                'verbose_name_plural': 'Quadrant Usage Events',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['created_at'], name='platform_co_created_df67f8_idx'),
                    models.Index(fields=['hour', 'created_at'], name='platform_co_hour_2ef832_idx'),
                    models.Index(fields=['slug', 'created_at'], name='platform_co_slug_cd036e_idx'),
                ],
            },
        ),
    ]
