# Generated by Django 6.0.5 on 2026-07-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0018_reference_datasets'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gicsreference',
            new_name='platform_co_level_60ea83_idx',
            old_name='platform_co_level_3b70f8_idx',
        ),
        migrations.RenameIndex(
            model_name='gicsreference',
            new_name='platform_co_parent__1e8635_idx',
            old_name='platform_co_parent__24ee9b_idx',
        ),
        migrations.RenameIndex(
            model_name='gicsreference',
            new_name='platform_co_is_acti_8d8970_idx',
            old_name='platform_co_is_acti_f3ab40_idx',
        ),
        migrations.RenameIndex(
            model_name='mlasclassificationrecord',
            new_name='platform_co_review__208db2_idx',
            old_name='platform_co_review__72dbd8_idx',
        ),
        migrations.RenameIndex(
            model_name='mlasclassificationrecord',
            new_name='platform_co_mlas_su_9777b1_idx',
            old_name='platform_co_mlas_s_f3c880_idx',
        ),
        migrations.RenameIndex(
            model_name='mlasclassificationrecord',
            new_name='platform_co_target__b3635f_idx',
            old_name='platform_co_target__36cded_idx',
        ),
        migrations.RenameIndex(
            model_name='naicsreference',
            new_name='platform_co_sector__ed90db_idx',
            old_name='platform_co_sector__99cb49_idx',
        ),
        migrations.RenameIndex(
            model_name='naicsreference',
            new_name='platform_co_is_acti_e6ca9e_idx',
            old_name='platform_co_is_acti_93dcb8_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticbundle',
            new_name='platform_co_family_3ee1a1_idx',
            old_name='platform_co_family_417313_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticbundlerevision',
            new_name='platform_co_bundle__5857ee_idx',
            old_name='platform_co_bundle__4dc235_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticbundlerevisiontag',
            new_name='platform_co_bundle__a71eb9_idx',
            old_name='platform_co_bundle__29f6ff_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticbundlerevisiontag',
            new_name='platform_co_bundle__7077a9_idx',
            old_name='platform_co_bundle__78d723_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticbundleshare',
            new_name='platform_co_bundle__277950_idx',
            old_name='platform_co_bundle__0a8a2f_idx',
        ),
    ]
