# Generated by Django 6.0.5 on 2026-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
    ]
