# Generated by Django 6.0.5 on 2026-06-28 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_1_label', models.CharField(default='CP', max_length=120)),
                ('compartment_2_label', models.CharField(default='IN', max_length=120)),
                ('compartment_3_label', models.CharField(default='DC', max_length=120)),
                ('compartment_4_label', models.CharField(default='NO', max_length=120)),
                ('compartment_5_label', models.CharField(default='BOT', max_length=120)),
                ('compartment_6_label', models.CharField(default='Analyze', max_length=120)),
                ('compartment_7_label', models.CharField(default='Evaluate', max_length=120)),
                ('compartment_8_label', models.CharField(default='Persuasive', max_length=120)),
                ('compartment_9_label', models.CharField(default='PTG', max_length=120)),
                ('compartment_10_label', models.CharField(default='PH&D', max_length=120)),
                ('compartment_11_label', models.CharField(default='LW', max_length=120)),
                ('compartment_12_label', models.CharField(default='TR', max_length=120)),
                ('board_corporation_label', models.CharField(default='Personal Corporation', max_length=160)),
                ('board_museum_label', models.CharField(default='Personal Museum', max_length=160)),
                ('board_garden_label', models.CharField(default='Personal Garden', max_length=160)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
