# Generated by Django 6.0.5 on 2026-08-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainprofile',
            name='board_corporation_label',
            field=models.CharField(default='Personal Corporation', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='board_garden_label',
            field=models.CharField(default='Personal Garden', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='board_museum_label',
            field=models.CharField(default='Personal Museum', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_10_label',
            field=models.CharField(default='PH&D', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_11_label',
            field=models.CharField(default='LW', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_12_label',
            field=models.CharField(default='TR', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_1_label',
            field=models.CharField(default='CP', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_2_label',
            field=models.CharField(default='IN', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_3_label',
            field=models.CharField(default='DC', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_4_label',
            field=models.CharField(default='NO', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_5_label',
            field=models.CharField(default='BOT', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_6_label',
            field=models.CharField(default='Analyze', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_7_label',
            field=models.CharField(default='Evaluate', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_8_label',
            field=models.CharField(default='Persuasive', max_length=36),
        ),
        migrations.AlterField(
            model_name='domainprofile',
            name='compartment_9_label',
            field=models.CharField(default='PTG', max_length=36),
        ),
    ]
