# Generated by Django 6.0.5 on 2026-06-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationitem',
            name='work_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporationitem',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporationitem',
            name='work_status',
            field=models.CharField(blank=True, choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20, null=True),
        ),
    ]
