# Generated by Django 6.0.5 on 2026-08-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_corporationitem_work_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationitem',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
    ]
