# Generated by Django 6.0.5 on 2026-06-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(default='BaseTrue Monthly', max_length=120)),
                ('masthead_title', models.CharField(default='The BaseTrue Bulletin', max_length=180)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('tagline', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_issue_month_year')],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('pip', 'Perpetual Infrastructure Program'), ('base_true', 'Base True Information Format')], max_length=20)),
                ('headline', models.CharField(max_length=220)),
                ('byline', models.CharField(max_length=120)),
                ('dek', models.CharField(blank=True, max_length=280)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(help_text='Set a future date to stage stories ahead of release.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='baseTrue_news.issue')),
            ],
            options={
                'ordering': ['feature', 'publish_at', 'id'],
            },
        ),
    ]
