# Generated by Django 6.0.5 on 2026-07-04 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('short_series', 'Short Series (Sitcom)'), ('one_hour_series', '1-Hour Long Series Episode'), ('movie', 'Movie (90–120 minutes)'), ('epic_movie', 'Epic Movie (3+ hours)')], default='movie', max_length=20)),
                ('talking_points', models.TextField(blank=True)),
                ('core_concept', models.TextField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story Entry',
                'verbose_name_plural': 'Story Entries',
                'ordering': ['entry_id'],
            },
        ),
    ]
