# Generated by Django 6.0.5 on 2026-07-05 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('preset_type', models.CharField(choices=[('search', 'Search Preset'), ('cluster', 'Cluster Preset')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['preset_type', 'name'],
                'unique_together': {('owner', 'preset_type', 'name')},
            },
        ),
    ]
