# Generated by Django 6.0.5 on 2026-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytelling_dashboard', '0005_seed_admin_story_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticpreset',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='storysession',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
    ]
