# Generated by Django 6.0.5 on 2026-07-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('povs', '0002_povresponse_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='povresponse',
            options={'ordering': ['-updated_at']},
        ),
    ]
