# Generated by Django 6.0.5 on 2026-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeidea',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]