# Generated by Django 6.0.5 on 2026-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twist', '0002_creativeidea_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeidea',
            name='status',
            field=models.CharField(
                choices=[('raw', 'Raw'), ('developed', 'Developed'), ('archived', 'Archived')],
                default='raw',
                max_length=20,
            ),
        ),
    ]
