# Generated by Django 6.0.5 on 2026-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twist', '0004_update_status_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeidea',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('personal', 'Personal')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='creativeidea',
            name='status',
            field=models.CharField(choices=[('RAW', 'Raw'), ('SEED', 'Seed'), ('PROJECT', 'Project'), ('BUSINESS', 'Business (Legacy)')], default='RAW', max_length=20),
        ),
    ]
