# Generated by Django 6.0.5 on 2026-06-24 02:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvectionCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_index', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('world_clock_hour', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('label', models.CharField(max_length=120)),
                ('lattice_coordinate', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['compartment_index'],
            },
        ),
        migrations.CreateModel(
            name='IndustryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(help_text='Industry group number 1-16.', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('sector', models.CharField(choices=[('A', 'Primary'), ('B', 'Secondary'), ('C', 'Tertiary'), ('D', 'Quaternary')], max_length=1)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BaseTrueSquareRootMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(max_length=150)),
                ('lattice_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pip_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['territory_name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='peringram.industrygroup')),
            ],
            options={
                'ordering': ['group__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RecycleThreeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_rd', models.DecimalField(decimal_places=2, default=Decimal('33.33'), max_digits=5)),
                ('people_small_business_qcqa', models.DecimalField(decimal_places=2, default=Decimal('33.33'), max_digits=5)),
                ('government_infrastructure_protection', models.DecimalField(decimal_places=2, default=Decimal('33.34'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='peringram.industry')),
            ],
            options={
                'ordering': ['industry__group__code', 'industry__code', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(fields=('group', 'code'), name='unique_industry_code_per_group'),
        ),
        migrations.AddConstraint(
            model_name='subindustry',
            constraint=models.UniqueConstraint(fields=('industry', 'code'), name='unique_sub_industry_code_per_industry'),
        ),
    ]
