# Generated by Django 6.0.5 on 2026-06-24 02:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peringram', '0002_alter_industry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclethreeallocation',
            name='government_infrastructure_protection',
            field=models.DecimalField(decimal_places=2, default=Decimal('33.33'), max_digits=5),
        ),
    ]
