# Generated by Django 6.0.5 on 2026-06-24 02:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peringram', '0003_alter_recyclethreeallocation_government_infrastructure_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclethreeallocation',
            name='isea_gdp_optimization',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional ISEA GDP optimization amount (0.00 or 0.01).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('0.01'))]),
        ),
    ]
