# Generated by Django 6.0.5 on 2026-06-24 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peringram', '0005_alter_recyclethreeallocation_isea_gdp_optimization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrygroup',
            name='code',
            field=models.PositiveSmallIntegerField(help_text='Industry group number 1-64.', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)]),
        ),
    ]
