# Generated by Django 6.0.5 on 2026-06-24 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peringram', '0006_alter_industrygroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrygroup',
            name='code',
            field=models.PositiveSmallIntegerField(help_text='Industry group number 1-16.', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
