# Generated by Django 6.0.5 on 2026-07-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peringram', '0010_rename_recycle3profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLatticeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('lattice_compartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_users', to='peringram.latticecompartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lattice_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
